os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-gnu

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false
test_script:
  - cargo test --all --verbose --features collectd-55
